<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class SeedTovariTransportMore extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tovari_transport = [
        	[
	            'from_lat' => 43.218199,
	            'from_lng' => 27.932893,
	            'to_lat' => 42.510784,
	            'to_lng' => 27.451005,
	            'from_city' => "Варна",
	            'to_city' => "Бургас",
	            'description' => '',
	            'price' => 32,
	            'to_date' => '2020-04-07 10:10:10',
	            'fast_payment' => 1,
	            'adr' => 0,
	            'type' => 1,
	            'tov_trans_types' => 1,
	            'firm_id' => 1,
	            'vehicle_type' => 1,
    	    ],
    	    [
	            'from_lat' => 43.218199,
	            'from_lng' => 27.932893,
	            'to_lat' => 42.510784,
	            'to_lng' => 27.451005,
	            'from_city' => "Варна",
	            'to_city' => "Бургас",
	            'description' => '',
	            'price' => 32,
	            'to_date' => '2020-04-07 10:10:10',
	            'fast_payment' => 1,
	            'adr' => 1,
	            'type' => 0,
	            'tov_trans_types' => 3,
	            'firm_id' => 1,
	            'vehicle_type' => 3,
    	    ],
    	    [
	            'from_lat' => 43.218199,
	            'from_lng' => 27.932893,
	            'to_lat' => 42.510784,
	            'to_lng' => 27.451005,
	            'from_city' => "Варна",
	            'to_city' => "Бургас",
	            'description' => '',
	            'price' => 32,
	            'to_date' => '2020-04-12 10:10:10',
	            'fast_payment' => 1,
	            'adr' => 0,
	            'type' => 1,
	            'tov_trans_types' => 2,
	            'firm_id' => 1,
	            'vehicle_type' => 3,
    	    ],
    	    [
	            'from_lat' => 43.218199,
	            'from_lng' => 27.932893,
	            'to_lat' => 42.510784,
	            'to_lng' => 27.451005,
	            'from_city' => "Варна",
	            'to_city' => "Бургас",
	            'description' => '',
	            'price' => 32,
	            'to_date' => '2020-04-12 10:10:10',
	            'fast_payment' => 1,
	            'adr' => 1,
	            'type' => 0,
	            'tov_trans_types' => 2,
	            'firm_id' => 1,
	            'vehicle_type' => 2,
    	    ],
    	    [
	            'from_lat' => 43.218199,
	            'from_lng' => 27.932893,
	            'to_lat' => 42.510784,
	            'to_lng' => 27.451005,
	            'from_city' => "Варна",
	            'to_city' => "Бургас",
	            'description' => '',
	            'price' => 500,
	            'to_date' => '2020-04-15 10:10:10',
	            'fast_payment' => 1,
	            'adr' => 0,
	            'type' => 1,
	            'tov_trans_types' => 1,
	            'firm_id' => 1,
	            'vehicle_type' => 1,
    	    ],
    	    [
	            'from_lat' => 43.218199,
	            'from_lng' => 27.932893,
	            'to_lat' => 42.510784,
	            'to_lng' => 27.451005,
	            'from_city' => "Варна",
	            'to_city' => "Бургас",
	            'description' => '',
	            'price' => 600,
	            'to_date' => '2020-04-21 10:10:10',
	            'fast_payment' => 1,
	            'adr' => 1,
	            'type' => 0,
	            'tov_trans_types' => 5,
	            'firm_id' => 1,
	            'vehicle_type' => 5,
    	    ],
    	    [
	            'from_lat' => 43.218199,
	            'from_lng' => 27.932893,
	            'to_lat' => 42.510784,
	            'to_lng' => 27.451005,
	            'from_city' => "Варна",
	            'to_city' => "Бургас",
	            'description' => '',
	            'price' => 32,
	            'to_date' => '2020-04-21 10:10:10',
	            'fast_payment' => 1,
	            'adr' => 0,
	            'type' => 1,
	            'tov_trans_types' => 4,
	            'firm_id' => 1,
	            'vehicle_type' => 4,
    	    ],
    	    [
	            'from_lat' => 43.218199,
	            'from_lng' => 27.932893,
	            'to_lat' => 42.510784,
	            'to_lng' => 27.451005,
	            'from_city' => "Варна",
	            'to_city' => "Бургас",
	            'description' => '',
	            'price' => 32,
	            'to_date' => '2020-07-05 10:10:10',
	            'fast_payment' => 1,
	            'adr' => 0,
	            'type' => 0,
	            'tov_trans_types' => 2,
	            'firm_id' => 1,
	            'vehicle_type' => 2,
    	    ],
    	    [
	            'from_lat' => 43.218199,
	            'from_lng' => 27.932893,
	            'to_lat' => 42.510784,
	            'to_lng' => 27.451005,
	            'from_city' => "Варна",
	            'to_city' => "Бургас",
	            'description' => '',
	            'price' => 32,
	            'to_date' => '2020-07-05 10:10:10',
	            'fast_payment' => 1,
	            'adr' => 0,
	            'type' => 1,
	            'tov_trans_types' => 3,
	            'firm_id' => 1,
	            'vehicle_type' => 3,
    	    ],
    	    [
	            'from_lat' => 43.218199,
	            'from_lng' => 27.932893,
	            'to_lat' => 42.510784,
	            'to_lng' => 27.451005,
	            'from_city' => "Варна",
	            'to_city' => "Бургас",
	            'description' => '',
	            'price' => 32,
	            'to_date' => '2020-07-05 10:10:10',
	            'fast_payment' => 1,
	            'adr' => 1,
	            'type' => 0,
	            'tov_trans_types' => 3,
	            'firm_id' => 1,
	            'vehicle_type' => 5,
    	    ],
    	    [
	            'from_lat' => 43.218199,
	            'from_lng' => 27.932893,
	            'to_lat' => 42.510784,
	            'to_lng' => 27.451005,
	            'from_city' => "Варна",
	            'to_city' => "Бургас",
	            'description' => '',
	            'price' => 32,
	            'to_date' => '2020-07-05 10:10:10',
	            'fast_payment' => 1,
	            'adr' => 0,
	            'type' => 1,
	            'tov_trans_types' => 1,
	            'firm_id' => 1,
	            'vehicle_type' => 4,
    	    ],
    	    [
	            'from_lat' => 43.218199,
	            'from_lng' => 27.932893,
	            'to_lat' => 42.510784,
	            'to_lng' => 27.451005,
	            'from_city' => "Варна",
	            'to_city' => "Бургас",
	            'description' => '',
	            'price' => 32,
	            'to_date' => '2020-07-05 10:10:10',
	            'fast_payment' => 1,
	            'adr' => 1,
	            'type' => 0,
	            'tov_trans_types' => 3,
	            'firm_id' => 1,
	            'vehicle_type' => 1,
    	    ],
    	    [
	            'from_lat' => 43.218199,
	            'from_lng' => 27.932893,
	            'to_lat' => 42.510784,
	            'to_lng' => 27.451005,
	            'from_city' => "Варна",
	            'to_city' => "Бургас",
	            'description' => '',
	            'price' => 32,
	            'to_date' => '2020-07-05 10:10:10',
	            'fast_payment' => 1,
	            'adr' => 0,
	            'type' => 1,
	            'tov_trans_types' => 2,
	            'firm_id' => 1,
	            'vehicle_type' => 1,
    	    ],
    	    [
	            'from_lat' => 43.218199,
	            'from_lng' => 27.932893,
	            'to_lat' => 42.510784,
	            'to_lng' => 27.451005,
	            'from_city' => "Варна",
	            'to_city' => "Бургас",
	            'description' => '',
	            'price' => 32,
	            'to_date' => '2020-07-05 10:10:10',
	            'fast_payment' => 1,
	            'adr' => 1,
	            'type' => 0,
	            'tov_trans_types' => 4,
	            'firm_id' => 1,
	            'vehicle_type' => 2,
    	    ],
    	    
        ];
        DB::table('tovari_transport')->insert($tovari_transport);
    }
}
